# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

info:
  build:
    artifact: <%=baseName%>
    version: 0.0.0
    description: Change Me Plz!!

server:
  port: 9990
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

stormpath:
  application:
    url:
  api:
    key:
      id:
      secret:

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false

    messageSource:
        cacheSeconds: 1

jwt:
   token:
      signing-key: |
         -----BEGIN RSA PRIVATE KEY-----
         MIIEowIBAAKCAQEAmSsiuAwf6FL5KBhT5t0aqiWg0b0XTG/xSAqSUD/cIbLNMs4Y
         pk1UfPyZxDoMZjQRsf/6G233+XDzXkwSzuX1xmV36zAo5IlHFpUVBhRQCjjncHbz
         ShUPl84sdNuh1NcBWKIsu7m4FwQu3lBWv0gM0CLfnDmpkkYLo8LWKxOOqhjpgYKD
         QsJ2tilUmpYbtnoYHQgdcA3y+KU1lbJbCfRrHzsJyrGpk41TFmWsWe0yWUhHwKaN
         cksbLMx0izEi36lIFBR4UBxSAjMO4UqvU6j2cNX/wlhMnhv2yE6wUecpwG7jE7zl
         9CdGMXLwgXfxlF00ItsMTVs+GDbm28hdlXDNBQIDAQABAoIBACxTdWq554n+aSiX
         UcCgABV5aj8Ib/Oo+bSVip46vOPrsMKhLjUCcA7zszQ8cFYrf2t53tGNU5QWgfeq
         IE9L8YKG3ttrRopMyAva/QiTXE55BVFguyuXSLnv6qGu5fiIeFVEKZnyNzpB9aZU
         raYRndOmI/w8G7y/FKNBwWUZ9dF3jYd1umZI2ILYCVeE1Pflk6V1O3eNooyTqbyp
         Hzgfaaxk5umSqneJ1eRc3E+7dXb4oVbF4Fysx3Z9IzutvoBrget1nLQt7NAxwIwX
         pBR5IfGi6mZLYP5TyqIAzdxR+jbXb8dJ/Ww5IttFOlO+C6kR96X13Rhj5CM9xtzv
         GdnOqUECgYEAyqI/8FAWFYsZO17BO/qhdTbS+QRj7FVK36lIWppQaUvzYL1QTNkq
         2uSr3u84uuOeTlQXrhHFO1HcyNmUa3nY79AQU1QWSKSXs4SrjGg3UKdnfT/ZipAI
         UEN1VF7tHW2cG/CrX5oX45YowtQVL97xnBxvq1vSaq3jj2cLphlMyd0CgYEAwYHk
         XGqgFfZjDcQ9BEatefW33q4c1lAfUaB2sPiUyMk60d0Cf7YyPGVpj+mkR7LO0biy
         TXU9f0ZKN8pTt7gtcsMsEaGiMXPe49qiiRjHwhhNK26u7YyKePP4ioBh3cWdGiOO
         uJ1oIeR5UXzJ3HkrxDDj5m8GKN5M1ZH5VqOg4UkCgYEAm2oP8ifqmEFka9XEDVWw
         ai9PZrCIVyYf1CWJGfyLOgeHtiXdJePWa6bBb64465ZSv67drqNwi4vA88d1f20o
         Bt6k9tRidvrOY2CZFoqECncq97R2DEFmLvFeVwSrhkugVQmk1yFfuy1bO/rf+SRc
         WSiyOVKmsy2FgGI/W/jBnX0CgYBmgocVJi8UM2gZ/OFOCJsRxsfXIWmJZvyQY289
         JRK8o02Tq38NZNmMATVA1cb/bIv/sdZTDk67w+LBV1+uLdV1vEr2NCgWBooHLuV3
         tzbrbbBD1+i3UwJwPN5nkMdHks488KVEy65EdiKGtpLBRzeWQUgZ5Krgr5MIeMIb
         0acCcQKBgGvSe11qLuAdI5iNTL07dTIibFcYcKAkJYIyJS/34SUgTWMTk31Xzk2l
         Bv+JbAJKA9D7dwee76UZJjM9abCM1FBWV26DyWbBpSezb2I/BFEYbbTx8VOkBr40
         my42ilUmYyRkDjJ+U05JE2TLCtGasC8lYgInUEkmgDINkVXa1eRm
         -----END RSA PRIVATE KEY-----
      verification-key: |
         -----BEGIN PUBLIC KEY-----
         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmSsiuAwf6FL5KBhT5t0a
         qiWg0b0XTG/xSAqSUD/cIbLNMs4Ypk1UfPyZxDoMZjQRsf/6G233+XDzXkwSzuX1
         xmV36zAo5IlHFpUVBhRQCjjncHbzShUPl84sdNuh1NcBWKIsu7m4FwQu3lBWv0gM
         0CLfnDmpkkYLo8LWKxOOqhjpgYKDQsJ2tilUmpYbtnoYHQgdcA3y+KU1lbJbCfRr
         HzsJyrGpk41TFmWsWe0yWUhHwKaNcksbLMx0izEi36lIFBR4UBxSAjMO4UqvU6j2
         cNX/wlhMnhv2yE6wUecpwG7jE7zl9CdGMXLwgXfxlF00ItsMTVs+GDbm28hdlXDN
         BQIDAQAB
         -----END PUBLIC KEY-----
