# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

server:
  port: 9990

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false

    messageSource:
        cacheSeconds: 1
