spring:
    profiles: dev

    jpa:
        database-platform: <%=packageName%>.hibernate.CustomPostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.generate_statistics: true

    thymeleaf:
        mode: XHTML
        cache: false

database:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: postgres://<%= _.underscored(baseName) %>:<%= _.underscored(baseName) %>@localhost:5432/<%= _.underscored(baseName) %>

metrics:
    jmx.enabled: true

stormpath:
  app:
    name: <%=baseName%>-dev
  api:
    key:
      file:
        location: <%= _.unescape('\$\{HOME}/.config/stormpath/apiKey.properties')%>
      id:
      secret:
