# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

info:
  build:
    artifact: <%=baseName%>
    version: 0.0.0
    description: Change Me Plz!!

server:
  port: 9990
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

stormpath:
  applicationUrl:
  apiKeyId:
  apiKeySecret:

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false

    messageSource:
        cacheSeconds: 1
