spring:
    profiles: prod

    jpa:
        database-platform: <%=packageName%>.hibernate.CustomPostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.generate_statistics: false

    thymeleaf:
        mode: XHTML
        cache: true

database:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: postgres://<%= _.underscored(baseName) %>:<%= _.underscored(baseName) %>@localhost:5432/<%= _.underscored(baseName) %>

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:
